server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://47.108.167.244:3306/ycj_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 47.108.167.244
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml